version: '3.8'

services:
  fonoster-server:
    image: fonoster-server:latest
    container_name: fonoster-server
    build:
      context: ./fonoster-server
      dockerfile: Containerfile
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - FONOSTER_ACCESS_KEY_ID=${FONOSTER_ACCESS_KEY_ID:-}
      - FONOSTER_API_KEY=${FONOSTER_API_KEY:-}
      - FONOSTER_API_SECRET=${FONOSTER_API_SECRET:-}
      - FONOSTER_ENDPOINT=${FONOSTER_ENDPOINT:-https://api.fonoster.com}
      - FONOSTER_FROM_NUMBER=${FONOSTER_FROM_NUMBER:-}
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3001/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  backend:
    image: google-intelligent-backend:latest
    container_name: google-intelligent-backend
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "8000:8000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - FONOSTER_SERVER_URL=http://fonoster-server:3001
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - PYTHONUNBUFFERED=1
    depends_on:
      fonoster-server:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import httpx; httpx.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  frontend:
    image: google-intelligent-frontend:latest
    container_name: google-intelligent-frontend
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  app-network:
    driver: bridge

